--drop table worksat;
--drop table securityguard;
--drop table ticketagent;
--drop table employee;
drop table securityguardemployee;
drop table ticketagentemployee;
drop table flieswith;
drop table airplane;
drop table confirms;
drop table books;
drop table addson;
drop table mealplan;
drop table planeticket;
drop table carries;
drop table luggage;
drop table passenger;
--drop table destinesAt;
--drop table originatesFrom;
drop table fliesFromTo;
drop table controls;
drop table airport;
drop table flight;

exit;
